"use client";
import { FormattedMessage } from "react-intl";
import { militaryOverseasResources } from "@/lib/militaryOverseas";

export default function MilitaryOverseasPage() {
  return <main className="max-w-4xl mx-auto px-4 py-10 space-y-8">
    <header><h1 className="text-3xl font-bold"><FormattedMessage id="military.title" defaultMessage="Military and overseas voting" /></h1><p className="mt-2 text-gray-600"><FormattedMessage id="military.subtitle" defaultMessage="Official guidance without entering an address or creating an account." /></p></header>
    <section className="grid gap-5 sm:grid-cols-2" aria-label="Voting guidance"><article className="border rounded-xl p-5"><h2 className="font-semibold"><FormattedMessage id="military.fpca" defaultMessage="Register with the FPCA" /></h2><p className="mt-2 text-sm text-gray-600"><FormattedMessage id="military.fpcaBody" defaultMessage="The Federal Post Card Application lets eligible military and overseas voters register and request ballots from their voting residence." /></p><a className="underline" href="https://www.fvap.gov/fpca-embassy" target="_blank" rel="noopener noreferrer">FVAP FPCA guidance</a></article><article className="border rounded-xl p-5"><h2 className="font-semibold"><FormattedMessage id="military.fwab" defaultMessage="Use the FWAB when necessary" /></h2><p className="mt-2 text-sm text-gray-600"><FormattedMessage id="military.fwabBody" defaultMessage="The Federal Write-In Absentee Ballot may provide an emergency backup. Follow your state office instructions and deadlines." /></p><a className="underline" href="https://www.fvap.gov/fwab-eligibility" target="_blank" rel="noopener noreferrer">FVAP FWAB guidance</a></article></section>
    <section className="border rounded-xl p-5"><h2 className="font-semibold"><FormattedMessage id="military.residence" defaultMessage="Voting residence and mailing address" /></h2><p className="mt-2 text-sm text-gray-600"><FormattedMessage id="military.residenceBody" defaultMessage="Your voting residence is generally the last place you lived before leaving the country; your mailing address is where election materials can reach you. They can be different. If you have never resided in the United States, ask the state election office about the parent’s last voting residence." /></p></section>
    <section><h2 className="text-xl font-semibold"><FormattedMessage id="military.resources" defaultMessage="State election offices" /></h2><ul className="mt-3 grid grid-cols-2 sm:grid-cols-5 gap-2">{militaryOverseasResources.map((r) => <li key={r.state}><a className="underline" href={r.stateOfficeUrl} target="_blank" rel="noopener noreferrer">{r.state}</a> <span className="text-xs text-gray-500">{r.review}</span></li>)}</ul></section>
  </main>;
}
